## Creating .smi file for descriptor calculation

In [1]:
import pandas as pd
import os

In [2]:
df = pd.read_csv("alt_active_final.csv")
df

,cid,cmpdname,CanonicalSMILES,activity
0,653949,4-chloro-7-(ethylamino)chromen-2-one,CCNC1=CC2=C(C=C1)C(=CC(=O)O2)Cl,Active
1,969516,"(1E,6E)-1,7-bis(4-hydroxy-3-methoxyphenyl)hept...",COC1=C(C=CC(=C1)C=CC(=O)CC(=O)C=CC2=CC(=C(C=C2...,Active
2,658104,"methyl 5-(1-amino-5-morpholin-4-yl-6,7,8,9-tet...",COC(=O)C1=CC=C(O1)C2=C(C3=C(S2)N=C(C4=C3CCCC4)...,Active
3,100641,7-amino-4-(trifluoromethyl)chromen-2-one,C1=CC2=C(C=C1N)OC(=O)C=C2C(F)(F)F,Active
4,629074,"3-amino-4-(furan-2-yl)-6-phenylthieno[2,3-b]py...",C1=CC=C(C=C1)C2=NC3=C(C(=C2)C4=CC=CO4)C(=C(S3)...,Active
...,...,...,...,...
215,2463883,"4-[(Z)-[2-(3-methylphenyl)-1,3-dioxoisoquinoli...",CC1=CC(=CC=C1)N2C(=O)C3=CC=CC=C3C(=CC4=CC=C(C=...,Active
216,3934060,8-[5-(2-bromo-4-nitrophenyl)furan-2-yl]-7-(2-m...,CC(C)CN1C2=C(C(=O)NC1=O)N(C(=N2)C3=CC=C(O3)C4=...,Active
217,135440580,4-[(E)-C-methyl-N-(4-nitroanilino)carbonimidoy...,CC(=NNC1=CC=C(C=C1)[N+](=O)[O-])C2=CC=C(C=C2)O,Active
218,6451074,"(6aR,9R,9aR)-9-acetyl-3-[(1E,3E,5S)-3,5-dimeth...",CCC(C)C=C(C)C=CC1=CC2=CC(=O)C3(C(C2=CO1)C(C(=O...,Active
219,160115,"5,6,8-trihydroxy-2-methyl-9-(5,6,8-trihydroxy-...",CC1CC(=O)C2=C(O1)C=C3C(=C2O)C(=CC(=C3C4=C(C=C(...,Active

In [3]:
df = df.drop(['cmpdname', 'activity'], axis = 'columns')
df

           cid                                    CanonicalSMILES
0       653949                    CCNC1=CC2=C(C=C1)C(=CC(=O)O2)Cl
1       969516  COC1=C(C=CC(=C1)C=CC(=O)CC(=O)C=CC2=CC(=C(C=C2...
2       658104  COC(=O)C1=CC=C(O1)C2=C(C3=C(S2)N=C(C4=C3CCCC4)...
3       100641                  C1=CC2=C(C=C1N)OC(=O)C=C2C(F)(F)F
4       629074  C1=CC=C(C=C1)C2=NC3=C(C(=C2)C4=CC=CO4)C(=C(S3)...
..         ...                                                ...
215    2463883  CC1=CC(=CC=C1)N2C(=O)C3=CC=CC=C3C(=CC4=CC=C(C=...
216    3934060  CC(C)CN1C2=C(C(=O)NC1=O)N(C(=N2)C3=CC=C(O3)C4=...
217  135440580     CC(=NNC1=CC=C(C=C1)[N+](=O)[O-])C2=CC=C(C=C2)O
218    6451074  CCC(C)C=C(C)C=CC1=CC2=CC(=O)C3(C(C2=CO1)C(C(=O...
219     160115  CC1CC(=O)C2=C(O1)C=C3C(=C2O)C(=CC(=C3C4=C(C=C(...

[220 rows x 2 columns]

In [4]:
smiles = df.pop('CanonicalSMILES')
df.insert(0, 'CanonicalSMILES', smiles)
df

                                       CanonicalSMILES        cid
0                      CCNC1=CC2=C(C=C1)C(=CC(=O)O2)Cl     653949
1    COC1=C(C=CC(=C1)C=CC(=O)CC(=O)C=CC2=CC(=C(C=C2...     969516
2    COC(=O)C1=CC=C(O1)C2=C(C3=C(S2)N=C(C4=C3CCCC4)...     658104
3                    C1=CC2=C(C=C1N)OC(=O)C=C2C(F)(F)F     100641
4    C1=CC=C(C=C1)C2=NC3=C(C(=C2)C4=CC=CO4)C(=C(S3)...     629074
..                                                 ...        ...
215  CC1=CC(=CC=C1)N2C(=O)C3=CC=CC=C3C(=CC4=CC=C(C=...    2463883
216  CC(C)CN1C2=C(C(=O)NC1=O)N(C(=N2)C3=CC=C(O3)C4=...    3934060
217     CC(=NNC1=CC=C(C=C1)[N+](=O)[O-])C2=CC=C(C=C2)O  135440580
218  CCC(C)C=C(C)C=CC1=CC2=CC(=O)C3(C(C2=CO1)C(C(=O...    6451074
219  CC1CC(=O)C2=C(O1)C=C3C(=C2O)C(=CC(=C3C4=C(C=C(...     160115

[220 rows x 2 columns]

In [5]:
# creating a new directory in current directory for input and output descriptor files

os.mkdir('smi')
os.mkdir('des')

In [6]:
df.to_csv('smi/alt_active.smi', sep = '\t', index = False, header = False)